# Generated by Django 2.2.19 on 2022-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220327_1054'),
    ]


